WITH source_data AS (
    SELECT
        Date,
        CAST("EURUSD=X_Close" AS FLOAT64) AS EURUSD_Close,
        CAST("GBPUSD=X_Close" AS FLOAT64) AS GBPUSD_Close,
        CAST("JPYUSD=X_Close" AS FLOAT64) AS JPYUSD_Close
    FROM {{ target.project }}.{{ target.dataset }}.daily
)

SELECT
    Date,
    EURUSD_Close,
    GBPUSD_Close,
    JPYUSD_Close,
    
    AVG(EURUSD_Close) OVER (ORDER BY Date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS EURUSD_MA7,
    AVG(GBPUSD_Close) OVER (ORDER BY Date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS GBPUSD_MA7,
    AVG(JPYUSD_Close) OVER (ORDER BY Date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS JPYUSD_MA7,
    
    AVG(EURUSD_Close) OVER (ORDER BY Date ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS EURUSD_MA30,
    AVG(GBPUSD_Close) OVER (ORDER BY Date ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS GBPUSD_MA30,
    AVG(JPYUSD_Close) OVER (ORDER BY Date ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS JPYUSD_MA30

FROM source_data
ORDER BY Date
